// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: dots-and-boxes.proto
// Original file comments:
// Author: Martin Wistauder
// Version: 1.0
// Date: 11.12.2019
#ifndef GRPC_dots_2dand_2dboxes_2eproto__INCLUDED
#define GRPC_dots_2dand_2dboxes_2eproto__INCLUDED

#include "dots-and-boxes.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace dab {

}  // namespace dab


#endif  // GRPC_dots_2dand_2dboxes_2eproto__INCLUDED
