// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dots-and-boxes.proto

#ifndef PROTOBUF_INCLUDED_dots_2dand_2dboxes_2eproto
#define PROTOBUF_INCLUDED_dots_2dand_2dboxes_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_dots_2dand_2dboxes_2eproto 

namespace protobuf_dots_2dand_2dboxes_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[3];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_dots_2dand_2dboxes_2eproto
namespace dab {
class GameParameter;
class GameParameterDefaultTypeInternal;
extern GameParameterDefaultTypeInternal _GameParameter_default_instance_;
class GameState;
class GameStateDefaultTypeInternal;
extern GameStateDefaultTypeInternal _GameState_default_instance_;
class GameTurn;
class GameTurnDefaultTypeInternal;
extern GameTurnDefaultTypeInternal _GameTurn_default_instance_;
}  // namespace dab
namespace google {
namespace protobuf {
template<> ::dab::GameParameter* Arena::CreateMaybeMessage<::dab::GameParameter>(Arena*);
template<> ::dab::GameState* Arena::CreateMaybeMessage<::dab::GameState>(Arena*);
template<> ::dab::GameTurn* Arena::CreateMaybeMessage<::dab::GameTurn>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace dab {

// ===================================================================

class GameParameter : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:dab.GameParameter) */ {
 public:
  GameParameter();
  virtual ~GameParameter();

  GameParameter(const GameParameter& from);

  inline GameParameter& operator=(const GameParameter& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GameParameter(GameParameter&& from) noexcept
    : GameParameter() {
    *this = ::std::move(from);
  }

  inline GameParameter& operator=(GameParameter&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const GameParameter& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GameParameter* internal_default_instance() {
    return reinterpret_cast<const GameParameter*>(
               &_GameParameter_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(GameParameter* other);
  friend void swap(GameParameter& a, GameParameter& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GameParameter* New() const final {
    return CreateMaybeMessage<GameParameter>(NULL);
  }

  GameParameter* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<GameParameter>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const GameParameter& from);
  void MergeFrom(const GameParameter& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GameParameter* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint32 number_of_vertical_columns = 1;
  void clear_number_of_vertical_columns();
  static const int kNumberOfVerticalColumnsFieldNumber = 1;
  ::google::protobuf::uint32 number_of_vertical_columns() const;
  void set_number_of_vertical_columns(::google::protobuf::uint32 value);

  // uint32 number_of_horizontal_columns = 2;
  void clear_number_of_horizontal_columns();
  static const int kNumberOfHorizontalColumnsFieldNumber = 2;
  ::google::protobuf::uint32 number_of_horizontal_columns() const;
  void set_number_of_horizontal_columns(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:dab.GameParameter)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 number_of_vertical_columns_;
  ::google::protobuf::uint32 number_of_horizontal_columns_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_dots_2dand_2dboxes_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class GameTurn : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:dab.GameTurn) */ {
 public:
  GameTurn();
  virtual ~GameTurn();

  GameTurn(const GameTurn& from);

  inline GameTurn& operator=(const GameTurn& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GameTurn(GameTurn&& from) noexcept
    : GameTurn() {
    *this = ::std::move(from);
  }

  inline GameTurn& operator=(GameTurn&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const GameTurn& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GameTurn* internal_default_instance() {
    return reinterpret_cast<const GameTurn*>(
               &_GameTurn_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(GameTurn* other);
  friend void swap(GameTurn& a, GameTurn& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GameTurn* New() const final {
    return CreateMaybeMessage<GameTurn>(NULL);
  }

  GameTurn* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<GameTurn>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const GameTurn& from);
  void MergeFrom(const GameTurn& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GameTurn* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bool vertical = 1;
  void clear_vertical();
  static const int kVerticalFieldNumber = 1;
  bool vertical() const;
  void set_vertical(bool value);

  // uint32 target_column = 2;
  void clear_target_column();
  static const int kTargetColumnFieldNumber = 2;
  ::google::protobuf::uint32 target_column() const;
  void set_target_column(::google::protobuf::uint32 value);

  // uint32 target_gap = 3;
  void clear_target_gap();
  static const int kTargetGapFieldNumber = 3;
  ::google::protobuf::uint32 target_gap() const;
  void set_target_gap(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:dab.GameTurn)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool vertical_;
  ::google::protobuf::uint32 target_column_;
  ::google::protobuf::uint32 target_gap_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_dots_2dand_2dboxes_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class GameState : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:dab.GameState) */ {
 public:
  GameState();
  virtual ~GameState();

  GameState(const GameState& from);

  inline GameState& operator=(const GameState& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GameState(GameState&& from) noexcept
    : GameState() {
    *this = ::std::move(from);
  }

  inline GameState& operator=(GameState&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const GameState& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GameState* internal_default_instance() {
    return reinterpret_cast<const GameState*>(
               &_GameState_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(GameState* other);
  friend void swap(GameState& a, GameState& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GameState* New() const final {
    return CreateMaybeMessage<GameState>(NULL);
  }

  GameState* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<GameState>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const GameState& from);
  void MergeFrom(const GameState& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GameState* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bytes vertical_lines = 3;
  void clear_vertical_lines();
  static const int kVerticalLinesFieldNumber = 3;
  const ::std::string& vertical_lines() const;
  void set_vertical_lines(const ::std::string& value);
  #if LANG_CXX11
  void set_vertical_lines(::std::string&& value);
  #endif
  void set_vertical_lines(const char* value);
  void set_vertical_lines(const void* value, size_t size);
  ::std::string* mutable_vertical_lines();
  ::std::string* release_vertical_lines();
  void set_allocated_vertical_lines(::std::string* vertical_lines);

  // bytes horizontal_lines = 4;
  void clear_horizontal_lines();
  static const int kHorizontalLinesFieldNumber = 4;
  const ::std::string& horizontal_lines() const;
  void set_horizontal_lines(const ::std::string& value);
  #if LANG_CXX11
  void set_horizontal_lines(::std::string&& value);
  #endif
  void set_horizontal_lines(const char* value);
  void set_horizontal_lines(const void* value, size_t size);
  ::std::string* mutable_horizontal_lines();
  ::std::string* release_horizontal_lines();
  void set_allocated_horizontal_lines(::std::string* horizontal_lines);

  // uint32 vertical_columns = 1;
  void clear_vertical_columns();
  static const int kVerticalColumnsFieldNumber = 1;
  ::google::protobuf::uint32 vertical_columns() const;
  void set_vertical_columns(::google::protobuf::uint32 value);

  // uint32 horizontal_columns = 2;
  void clear_horizontal_columns();
  static const int kHorizontalColumnsFieldNumber = 2;
  ::google::protobuf::uint32 horizontal_columns() const;
  void set_horizontal_columns(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:dab.GameState)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr vertical_lines_;
  ::google::protobuf::internal::ArenaStringPtr horizontal_lines_;
  ::google::protobuf::uint32 vertical_columns_;
  ::google::protobuf::uint32 horizontal_columns_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_dots_2dand_2dboxes_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// GameParameter

// uint32 number_of_vertical_columns = 1;
inline void GameParameter::clear_number_of_vertical_columns() {
  number_of_vertical_columns_ = 0u;
}
inline ::google::protobuf::uint32 GameParameter::number_of_vertical_columns() const {
  // @@protoc_insertion_point(field_get:dab.GameParameter.number_of_vertical_columns)
  return number_of_vertical_columns_;
}
inline void GameParameter::set_number_of_vertical_columns(::google::protobuf::uint32 value) {
  
  number_of_vertical_columns_ = value;
  // @@protoc_insertion_point(field_set:dab.GameParameter.number_of_vertical_columns)
}

// uint32 number_of_horizontal_columns = 2;
inline void GameParameter::clear_number_of_horizontal_columns() {
  number_of_horizontal_columns_ = 0u;
}
inline ::google::protobuf::uint32 GameParameter::number_of_horizontal_columns() const {
  // @@protoc_insertion_point(field_get:dab.GameParameter.number_of_horizontal_columns)
  return number_of_horizontal_columns_;
}
inline void GameParameter::set_number_of_horizontal_columns(::google::protobuf::uint32 value) {
  
  number_of_horizontal_columns_ = value;
  // @@protoc_insertion_point(field_set:dab.GameParameter.number_of_horizontal_columns)
}

// -------------------------------------------------------------------

// GameTurn

// bool vertical = 1;
inline void GameTurn::clear_vertical() {
  vertical_ = false;
}
inline bool GameTurn::vertical() const {
  // @@protoc_insertion_point(field_get:dab.GameTurn.vertical)
  return vertical_;
}
inline void GameTurn::set_vertical(bool value) {
  
  vertical_ = value;
  // @@protoc_insertion_point(field_set:dab.GameTurn.vertical)
}

// uint32 target_column = 2;
inline void GameTurn::clear_target_column() {
  target_column_ = 0u;
}
inline ::google::protobuf::uint32 GameTurn::target_column() const {
  // @@protoc_insertion_point(field_get:dab.GameTurn.target_column)
  return target_column_;
}
inline void GameTurn::set_target_column(::google::protobuf::uint32 value) {
  
  target_column_ = value;
  // @@protoc_insertion_point(field_set:dab.GameTurn.target_column)
}

// uint32 target_gap = 3;
inline void GameTurn::clear_target_gap() {
  target_gap_ = 0u;
}
inline ::google::protobuf::uint32 GameTurn::target_gap() const {
  // @@protoc_insertion_point(field_get:dab.GameTurn.target_gap)
  return target_gap_;
}
inline void GameTurn::set_target_gap(::google::protobuf::uint32 value) {
  
  target_gap_ = value;
  // @@protoc_insertion_point(field_set:dab.GameTurn.target_gap)
}

// -------------------------------------------------------------------

// GameState

// uint32 vertical_columns = 1;
inline void GameState::clear_vertical_columns() {
  vertical_columns_ = 0u;
}
inline ::google::protobuf::uint32 GameState::vertical_columns() const {
  // @@protoc_insertion_point(field_get:dab.GameState.vertical_columns)
  return vertical_columns_;
}
inline void GameState::set_vertical_columns(::google::protobuf::uint32 value) {
  
  vertical_columns_ = value;
  // @@protoc_insertion_point(field_set:dab.GameState.vertical_columns)
}

// uint32 horizontal_columns = 2;
inline void GameState::clear_horizontal_columns() {
  horizontal_columns_ = 0u;
}
inline ::google::protobuf::uint32 GameState::horizontal_columns() const {
  // @@protoc_insertion_point(field_get:dab.GameState.horizontal_columns)
  return horizontal_columns_;
}
inline void GameState::set_horizontal_columns(::google::protobuf::uint32 value) {
  
  horizontal_columns_ = value;
  // @@protoc_insertion_point(field_set:dab.GameState.horizontal_columns)
}

// bytes vertical_lines = 3;
inline void GameState::clear_vertical_lines() {
  vertical_lines_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& GameState::vertical_lines() const {
  // @@protoc_insertion_point(field_get:dab.GameState.vertical_lines)
  return vertical_lines_.GetNoArena();
}
inline void GameState::set_vertical_lines(const ::std::string& value) {
  
  vertical_lines_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:dab.GameState.vertical_lines)
}
#if LANG_CXX11
inline void GameState::set_vertical_lines(::std::string&& value) {
  
  vertical_lines_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:dab.GameState.vertical_lines)
}
#endif
inline void GameState::set_vertical_lines(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  vertical_lines_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:dab.GameState.vertical_lines)
}
inline void GameState::set_vertical_lines(const void* value, size_t size) {
  
  vertical_lines_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:dab.GameState.vertical_lines)
}
inline ::std::string* GameState::mutable_vertical_lines() {
  
  // @@protoc_insertion_point(field_mutable:dab.GameState.vertical_lines)
  return vertical_lines_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GameState::release_vertical_lines() {
  // @@protoc_insertion_point(field_release:dab.GameState.vertical_lines)
  
  return vertical_lines_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GameState::set_allocated_vertical_lines(::std::string* vertical_lines) {
  if (vertical_lines != NULL) {
    
  } else {
    
  }
  vertical_lines_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), vertical_lines);
  // @@protoc_insertion_point(field_set_allocated:dab.GameState.vertical_lines)
}

// bytes horizontal_lines = 4;
inline void GameState::clear_horizontal_lines() {
  horizontal_lines_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& GameState::horizontal_lines() const {
  // @@protoc_insertion_point(field_get:dab.GameState.horizontal_lines)
  return horizontal_lines_.GetNoArena();
}
inline void GameState::set_horizontal_lines(const ::std::string& value) {
  
  horizontal_lines_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:dab.GameState.horizontal_lines)
}
#if LANG_CXX11
inline void GameState::set_horizontal_lines(::std::string&& value) {
  
  horizontal_lines_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:dab.GameState.horizontal_lines)
}
#endif
inline void GameState::set_horizontal_lines(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  horizontal_lines_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:dab.GameState.horizontal_lines)
}
inline void GameState::set_horizontal_lines(const void* value, size_t size) {
  
  horizontal_lines_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:dab.GameState.horizontal_lines)
}
inline ::std::string* GameState::mutable_horizontal_lines() {
  
  // @@protoc_insertion_point(field_mutable:dab.GameState.horizontal_lines)
  return horizontal_lines_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GameState::release_horizontal_lines() {
  // @@protoc_insertion_point(field_release:dab.GameState.horizontal_lines)
  
  return horizontal_lines_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GameState::set_allocated_horizontal_lines(::std::string* horizontal_lines) {
  if (horizontal_lines != NULL) {
    
  } else {
    
  }
  horizontal_lines_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), horizontal_lines);
  // @@protoc_insertion_point(field_set_allocated:dab.GameState.horizontal_lines)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace dab

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_dots_2dand_2dboxes_2eproto
